services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}  #idem MYSQL_DATABASE
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}  #idem MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - wordpress_net

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  #idem WORDPRESS_DB_PASSWORD
      MYSQL_DATABASE: ${MYSQL_DATABASE}   #idem WORDPRESS_DB_NAME
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress_net

networks:
  wordpress_net:
    driver: bridge


# services:
#   wordpress:
#     image: wordpress:latest
#     environment:
#       WORDPRESS_DB_NAME: wordpress
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: password
#       WORDPRESS_DB_HOST: db:3306
#     ports:
#       - "8000:80"
#     depends_on:
#       - db
#     networks:
#       - wordpress_net

#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: wordpress
#     networks:
#       - wordpress_net

# networks:
#   wordpress_net:
#     driver: bridge